version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-boilerplate"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tpwldsub62px"
s3_prefix = "sam-boilerplate"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

